export enum ErrorCode {
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE",
  UNAUTHORIZED = "UNAUTHORIZED",
  CANNOT_TARGET_SELF = "CANNOT_TARGET_SELF",
  CANNOT_RATE_OWN_RESOURCE = "CANNOT_RATE_OWN_RESOURCE",
}
