export enum PacketType {
  MESSAGE_RESPONSE = "MESSAGE_RESPONSE",
  MESSAGE_REQUEST = "MESSAGE_REQUEST",
  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_RESPONSE = "LOGIN_RESPONSE",
  ERROR = "ERROR",
  SYSTEM_MESSAGE = "SYSTEM_MESSAGE",
  USER_JOIN = "USER_JOIN",
  USER_LEAVE = "USER_LEAVE",
  ONLINE_USERS_REQUEST = "ONLINE_USERS_REQUEST",
  ONLINE_USERS_RESPONSE = "ONLINE_USERS_RESPONSE",
}

export type Packet = {
  type: PacketType;
};
